function reloadPage() {
    location.reload();
}
function changeText() {
    document.getElementById("demo").innerHTML = "Ramming Speed!"
}
function changeText2() {
    document.getElementById("demo").innerHTML = "Code zero zero zero. Destruct. Zero."
}


function getRandomImage() {  
//declare an array to store the images  
var randomImage = new Array();  
  
//insert the URL of images in array  
randomImage[0] = "Engineer.jpg";  
randomImage[1] = "TheLog.jpg";  
  
//generate a number and provide to the image to generate randomly  
var number = Math.floor(Math.random()*randomImage.length);  
  
//return the images generated by a random number  
return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';  
}
