function reloadPage() {
    location.reload();
}
function changeText() {
    document.getElementById("demo").innerHTML = "Ramming Speed!"
}
function changeText2() {
    document.getElementById("demo").innerHTML = "Code zero zero zero. Destruct. Zero."
}


function getRandomImage() {  
//declare an array to store the images  
var randomImage = new Array();  
  
//insert the URL of images in array  
randomImage[0] = "Images/Engineering.jpg";  
randomImage[1] = "Images/TheLog.jpg";  
  
//generate a number and provide to the image to generate randomly  
var number = Math.floor(Math.random()*randomImage.length);  
  
//return the images generated by a random number  
return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';  
}

/*
Declare an array using JavaScript to store the images.
Provide the link or URL of images in the declared array. You can also pass the height and width in the array for the image size to display on the webpage.
Declare a JavaScript variable to store a random value calculated using this floor(Math.random()*randomImage.length) method. It will generate a random number between 0 and the length of the array that will be assigned to the images to display randomly.
Now, return the random images selected using a number calculated in the previous step.
Put all the above steps in a user-defined function (getRandomImage), which will call by clicking on a Generate Image
In HTML code, we will use a tab and provide an ID to display an image over another image. So, the images will show you one by one, by overwrapping each other.
*/